apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-openvpn
spec:
  selector:
    matchLabels:
      app:  transmission-openvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  transmission-openvpn
    spec:
      volumes:
        {{ range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .path }}
        {{ end }}
      containers:
        - name:  transmission-openvpn
          image: docker.io/haugene/transmission-openvpn:latest
          ports:
            - containerPort: 9091
          env:
            - name: OPENVPN_PROVIDER
              value: {{ .Values.openvpn.provider | quote }}
            - name: OPENVPN_USERNAME
              value: {{ .Values.openvpn.username | quote }}
            - name: OPENVPN_PASSWORD
              value: {{ .Values.openvpn.password | quote }}
            - name: OPENVPN_CONFIG
              value: {{ .Values.openvpn.config | quote }}
            - name: LOCAL_NETWORK
              value: "10.0.0.0/8"
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: {{ .Values.downloadDir | quote }}
            - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
              value: "false"
            - name: PUID
              value: {{ .Values.puid | quote }}
            - name: PGID
              value: {{ .Values.pgid | quote }}
            - name: TRANSMISSION_WEB_UI
              value: "combustion"
            - name: TRANSMISSION_RATIO_LIMIT
              value: "0"
            - name: TRANSMISSION_RATIO_LIMIT_ENABLED
              value: "true"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            {{ range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{ end }}