apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.sharedIp | quote }}
spec:
  type: LoadBalancer
  ports:
    - port: 32400
  selector:
    app: plex
