apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app:  sonarr
  template:
    metadata:
      labels:
        app:  sonarr
    spec:
      volumes:
        {{ range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .path }}
        {{ end }}
      containers:
        - name:  sonarr
          image: docker.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: {{ .Values.puid | quote }}
            - name: PGID
              value: {{ .Values.pgid | quote }}
          volumeMounts:
            {{ range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{ end }}
