ingress:
  class: nginx
  annotations: {}
  tls:
    enabled: false
    host:

oauth2-proxy:
  config:
    clientID: 
    clientSecret:
    configFile:
  authenticatedEmailsFile:
    enabled: true
    restricted_access: