apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: rtsp-viewer
spec:
  rules:
    - http:
        paths:
          - backend:
              service: 
                name: rtsp-viewer
                port: 
                  number: 5000
            path: /
            pathType: Prefix
    {{ range .Values.cameras }}
    - http:
        paths:
          - backend:
              service: 
                name: rtsp-websocket-relay-{{ .name }}
                port: 
                  number: 8080
            path: /{{ .name }}
            pathType: Prefix
    {{ end }}