apiVersion: v1
kind: Service
metadata:
  name: rtsp-viewer
spec:
  ports:
    - port: 5000
  selector:
    app:  rtsp-viewer
{{ range .Values.cameras }}
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp-websocket-relay-{{ .name }}
spec:
  ports:
    - port: 8080
  selector:
    app: rtsp-websocket-relay-{{ .name }}
{{ end }}